# Utilise l'image officielle Node.js version 16.20.2
FROM node:16.20.2 AS build

# Définit le répertoire de travail dans le conteneur
WORKDIR /app

# Copie le fichier package.json et package-lock.json (si disponible)
COPY package*.json ./

# Installe les dépendances en utilisant npm avec --legacy-peer-deps
RUN npm install --legacy-peer-deps

# Copie le reste des fichiers de l'application dans le conteneur
COPY . .

# Exécute la commande de build
RUN npm run build:dev


# Utilise l'image officielle Node.js version 16.20.2
FROM node:16.20.2


COPY --from=build /app/dev dev

# Définit le dossier exposé
EXPOSE 3000

ENV REACT_APP_ENV=DEV
ENV IS_PRODUCTION=true
ENV SKIP_PREFLIGHT_CHECK=true
ENV REACT_APP_WEBAPI_URL=https://myconnectt-dev-api-h8hfcccufngyd5ag.northeurope-01.azurewebsites.net/
ENV REACT_APP_TENANT_ID=1
ENV REACT_APP_URL=https://myconnectt-front-dev-b3cseyd9gecvd2cv.northeurope-01.azurewebsites.net/
# Commande par défaut pour exécuter l'application
CMD ["npx", "serve", "-s", "dev"]