name: FRONT Build-Push Image and Deploy

on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: registryapiback.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker Image
      run: |
        docker build -f Dockerfile.DEV -t registryapiback.azurecr.io/myconnecttwebfront:dev-${{ github.sha }} .
        docker push registryapiback.azurecr.io/myconnecttwebfront:dev-${{ github.sha }}
      
    - name: Deploy App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myconnectt-front-dev'
        publish-profile: ${{ secrets.AZURE_FRONT_DEV_WEBAPP_PUBLISH_PROFILE }}
        images: 'registryapiback.azurecr.io/myconnecttwebfront:dev-${{ github.sha }}'
